apiVersion: v1
kind: Service
metadata:
  name: __SERVICE_NAME__
  namespace: __NAMESPACE__
  labels:
    app: __APP_LABEL__

spec:
  type: NodePort
  ports:
    - name: normal
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: __APP_LABEL__